pipeline {
    agent any

    environment {
        IMAGE_NAME = 'react-calculator'
        DOCKER_REGISTRY = 'your-dockerhub-username'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:latest deployment/'
            }
        }
        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh "echo $PASSWORD | docker login -u $USERNAME --password-stdin"
                    sh "docker push $DOCKER_REGISTRY/$IMAGE_NAME:latest"
                }
            }
        }
        stage('Deploy to K8s') {
            steps {
                sh "kubectl apply -f deployment/deployment.yaml"
                sh "kubectl apply -f deployment/service.yaml"
            }
        }
    }
}
